site_name: Techtonique/GPopt
theme:
  name: darkly # sandstone # slate # lux # darkly
  nav_style: dark
  #name: null
  #custom_dir: 'custom_theme/'

google_analytics: ['UA-146345113-2', 'https://techtonique.github.io/gpopt/']    

docs_dir: sources
# repo_url: https://github.com/Techtonique/GPopt
edit_uri: ""
site_description: 'Documentation for GPopt.'

nav:
    - Home: index.md
    - Documentation:
      - GPopt: documentation/gpopt.md    
    - Contributing: CONTRIBUTING.md  
    - License: LICENSE.md  
    - Techtonique: ../  